name: React App CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: yarn --frozen-lockfile
  #     - run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOST_DNS: ${{ secrets.HOST_DNS  }}
          USERNAME: ${{ secrets.USERNAME  }}

        run: |
          # Now we have got the access of EC2 and we will start the deploy .
          git checkout master &&
          git fetch --all &&
          git reset --hard origin/master &&
          git pull origin master &&
          sudo cp build/. -r /var/www/html
