name: React App CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checks-out repository under $GITHUB_WORKSPACE, so job can access it
        uses: actions/checkout@v3

      # - name: Install Dependencies and Build
      #   run: |
      #     yarn --frozen-lockfile
      #     yarn build

      - name: Deploy to server - sshpasss
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASS }}
        run: |
          chmod +x ./scripts/deploy_to_aws.sh && ./scripts/deploy_to_aws.sh
          sshpass -f pass_file ssh ec2-user@ec2-34-206-162-117.compute-1.amazonaws.com rm -rf /home/ec2-user/youtubeClone
        shell:
          bash
          # sudo apt-get update && sudo apt-get install -y sshpass
          # echo "$SSH_PASSWORD" > pass_file && chmod 0400 pass_file
          # sshpass -f pass_file ssh ec2-user@ec2-34-206-162-117.compute-1.amazonaws.com rm -rf /var/www/html/
          # sshpass -f pass_file scp -o StrictHostKeyChecking=no -r $GITHUB_WORKSPACE ec2-user@ec2-34-206-162-117.compute-1.amazonaws.com:/home/ec2-user
          # # sshpass -f pass_file ssh ec2-user@ec2-34-206-162-117.compute-1.amazonaws.com rm -rf /var/www/html/
          # # sshpass -f pass_file ssh ec2-user@ec2-34-206-162-117.compute-1.amazonaws.com cp -rf /home/ec2-user/youtubeClone/build /var/www/html
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Run sshpassx
  #       env:
  #         SSH_PASSWORD: ${{ secrets.SSH_PASS }}
  #       run: |
  #         sudo apt-get update && sudo apt-get install -y sshpass
  #         echo "$SSH_PASSWORD" > pass_file && chmod 0400 pass_file
  #         sshpass -f pass_file scp -o StrictHostKeyChecking=no -r $GITHUB_WORKSPACE ec2-user@ec2-34-206-162-117.compute-1.amazonaws.com:/home/ec2-user
  #         sshpass -f pass_file ssh ec2-user@ec2-34-206-162-117.compute-1.amazonaws.com cp /home/ec2-user/youtubeClone/build/. /var/www/html/
  #         sshpass -f pass_file ssh ec2-user@ec2-34-206-162-117.compute-1.amazonaws.com pwd
