name: React App CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: "yarn"

      - name: Checks-out repository under $GITHUB_WORKSPACE, so job can access it
        uses: actions/checkout@v3

      - name: Install Dependencies and Buildss
        run: |
          yarn --frozen-lockfile
          yarn build

      # - name: Deploy to server - sshpass
      #   env:
      #     SSH_PASSWORD: ${{ secrets.SSH_PASS }}
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y sshpass
      #     sudo apt-get install rsync

      #     sshpass -f pass_file rsync -ahv ssh -o StrictHostKeyChecking=no $GITHUB_WORKSPACE ec2-user@ec2-34-206-162-117.compute-1.amazonaws.com:/home/ec2-user/

      #     # sshpass -f pass_file ssh ec2-user@ec2-34-206-162-117.compute-1.amazonaws.com rm -rf /home/ec2-user/youtubeClone
      #     # chmod +x ./scripts/deploy_to_aws.sh && ./scripts/deploy_to_aws.sh
      #   shell: bash
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /home/ec2-user
